<?php
/**
 * Generated by universal php auto loader
 * @link http://github.com/dmkuznetsov/php-autoloader
 * @copyright Copyright (c) 2012-2013 Dmitry Kuznetsov <kuznetsov2d@gmail.com>
 * @license http://raw.github.com/dmkuznetsov/php-autoloader/master/LICENSE.txt New BSD License
 * @date 2013-04-14 21:31
 */
function __dm_autoload_runtime( $className )
{
	$map = array (
  'Dm\\Runtime' => 'src/Runtime.php',
  'Dm\\Runtime\\DisableFunction' => 'src/Runtime/DisableFunction.php',
  'Dm\\Runtime\\Exception' => 'src/Runtime/Exception.php',
  'Dm\\Runtime\\OverrideFunction' => 'src/Runtime/OverrideFunction.php',
  'Dm\\Runtime\\Parser' => 'src/Runtime/Parser.php',
);
	if ( !class_exists( $className, false ) && isset( $map[ $className ] ) )
	{
		include $map[ $className ];
	}
}
spl_autoload_register( '__dm_autoload_runtime' );
