<?php
/**
 * Generated by "Autoload generator"
 * @link http://github.com/dmkuznetsov/php-autoloader
 * @date 2013-11-07 23:41
 */
function __dm_autoload_runtime( $name )
{
	$map = array (
  'Dm\\Runtime\\Api' => 'source/Dm/Runtime/Api.php',
  'Dm\\Runtime\\DisableFunction' => 'source/Dm/Runtime/DisableFunction.php',
  'Dm\\Runtime\\Exception' => 'source/Dm/Runtime/Exception.php',
  'Dm\\Runtime\\OverrideFunction' => 'source/Dm/Runtime/OverrideFunction.php',
  'Dm\\Runtime\\Parser' => 'source/Dm/Runtime/Parser.php',
);
	if ( isset( $map[ $name ] ) )
	{
		require $map[ $name ];
	}
}
spl_autoload_register( '__dm_autoload_runtime' );
